// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations precisam de conexão direta/session (5432): o pooler em modo Transaction (6543)
    // não suporta advisory locks e faz o migrate travar. O app usa DATABASE_URL normalmente.
    url: process.env["DIRECT_URL"] ?? env("DATABASE_URL"),
  },
});
