export const HttpErrorType = {
    USER_EXISTS: "USER_EXISTS",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_DISABLED: "USER_DISABLED",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    FORBIDDEN: "FORBIDDEN",
    CRM_REQUIRED: "CRM_REQUIRED",
    CRM_EXISTS: "CRM_EXISTS",
    ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
    ROOM_IN_USE: "ROOM_IN_USE",
    APPOINTMENT_NOT_FOUND: "APPOINTMENT_NOT_FOUND",
    APPOINTMENT_CANCELLED: "APPOINTMENT_CANCELLED",
    APPOINTMENT_IN_PAST: "APPOINTMENT_IN_PAST",
    SELF_APPOINTMENT_NOT_ALLOWED: "SELF_APPOINTMENT_NOT_ALLOWED",
    ROOM_UNAVAILABLE: "ROOM_UNAVAILABLE",
    ROOM_BUSY: "ROOM_BUSY",
    DOCTOR_BUSY: "DOCTOR_BUSY",
    PATIENT_BUSY: "PATIENT_BUSY",
    EXAM_TYPE_NOT_FOUND: "EXAM_TYPE_NOT_FOUND",
    EXAM_TYPE_EXISTS: "EXAM_TYPE_EXISTS",
    EXAM_TYPE_DISABLED: "EXAM_TYPE_DISABLED",
    EXAM_TYPE_ALREADY_ACTIVE: "EXAM_TYPE_ALREADY_ACTIVE",
    APPOINTMENT_MISMATCH: "APPOINTMENT_MISMATCH",
    APPOINTMENT_NOT_ATTENDABLE: "APPOINTMENT_NOT_ATTENDABLE",
    EXAM_NOT_FOUND: "EXAM_NOT_FOUND",
    SELF_EXAMINATION_NOT_ALLOWED: "SELF_EXAMINATION_NOT_ALLOWED",
    PATIENT_NOT_FOUND: "PATIENT_NOT_FOUND",
    DOCTOR_NOT_FOUND: "DOCTOR_NOT_FOUND",
    DATABASE_UNREACHABLE: "DATABASE_UNREACHABLE",
    TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
} as const

export type HttpErrorType = (typeof HttpErrorType)[keyof typeof HttpErrorType]

export const HTTP_ERROR_MESSAGE: Record<HttpErrorType, string> = {
    USER_EXISTS: "Já existe um usuário cadastrado com esses dados.",
    USER_NOT_FOUND: "Usuário não encontrado.",
    USER_DISABLED: "Este usuário está desativado.",
    INVALID_CREDENTIALS: "E-mail ou senha inválidos.",
    FORBIDDEN: "Você não tem permissão para realizar esta ação.",
    CRM_REQUIRED: "Informe o CRM para usuários com role DOCTOR.",
    CRM_EXISTS: "Já existe um médico cadastrado com esse CRM.",
    ROOM_NOT_FOUND: "Sala não encontrada.",
    ROOM_IN_USE: "Não é possível excluir uma sala que possui agendamentos.",
    APPOINTMENT_NOT_FOUND: "Agendamento não encontrado.",
    APPOINTMENT_CANCELLED: "Este agendamento está cancelado e não pode ser alterado.",
    APPOINTMENT_IN_PAST: "O horário do agendamento deve estar no futuro.",
    SELF_APPOINTMENT_NOT_ALLOWED: "O médico não pode ser o próprio paciente do agendamento.",
    ROOM_UNAVAILABLE: "A sala não está disponível para agendamentos.",
    ROOM_BUSY: "A sala já possui um agendamento nesse horário.",
    DOCTOR_BUSY: "O médico já possui um agendamento nesse horário.",
    PATIENT_BUSY: "O paciente já possui um agendamento nesse horário.",
    EXAM_TYPE_NOT_FOUND: "Tipo de exame não encontrado.",
    EXAM_TYPE_EXISTS: "Já existe um tipo de exame com esse nome.",
    EXAM_TYPE_DISABLED: "Este tipo de exame está desativado.",
    EXAM_TYPE_ALREADY_ACTIVE: "Este tipo de exame já está ativo.",
    APPOINTMENT_MISMATCH: "O paciente e o médico do exame devem ser os mesmos do agendamento.",
    APPOINTMENT_NOT_ATTENDABLE: "O agendamento precisa estar confirmado ou atendido para registrar exames.",
    EXAM_NOT_FOUND: "Exame não encontrado.",
    SELF_EXAMINATION_NOT_ALLOWED: "O médico não pode ser o próprio paciente do exame.",
    PATIENT_NOT_FOUND: "Paciente não encontrado.",
    DOCTOR_NOT_FOUND: "Médico não encontrado.",
    DATABASE_UNREACHABLE: "Não foi possível conectar ao servidor. Tente novamente em alguns instantes.",
    TOO_MANY_REQUESTS: "Muitas requisições. Aguarde um momento e tente novamente.",
}
